#!/bin/sh

template="./template/default.html"
output_dir="./writing"

usage() {
    echo "Usage: ./$(basename $0) piece.org"
}

check_args() {
    if [ $# -eq 0 ]; then
        echo "$(tput bold)No file is specified!$(tput sgr0)"
        echo
        usage
        exit 1
    fi

    if [ "$1" == "-h" ]; then
        usage
        exit 0
    fi
}

build_css() {
    sassc -t compressed writing/css/style.scss writing/css/style.min.css
}

build_piece() {
    input=$1
    title="$(head -n 1 $input | sed 's/\*[ \t]//')"
    output="$output_dir/$(basename ${input%.*}).html"

    pandoc -s --template $template \
           --metadata pagetitle="$title" \
           --metadata date="$(date +"%-d %B %Y")" \
           -f org+smart $input -o $output

    echo "Created $output"
    open $output
}

build_sitemap() {
    cat <<EOF > sitemap.xml
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <url>
    <loc>https://sinasamavati.com/</loc>
    <priority>1</priority>
  </url>
  <url>
    <loc>https://sinasamavati.com/writing/</loc>
    <priority>0.8</priority>
  </url>
EOF

    for f in $(find writing -name '*.html' -a ! -name index.html); do
        cat <<EOF >> sitemap.xml
  <url>
    <loc>https://sinasamavati.com/$f</loc>
    <priority>0.5</priority>
  </url>
EOF
    done

    echo '</urlset>' >> sitemap.xml
}

check_args $@
build_css
build_piece $@
build_sitemap
